/var/slurm/spool/slurmd/job13458113/slurm_script: line 20: activate: No such file or directory
Traceback (most recent call last):
  File "/home/wrmf/AI2ES_5MinGrid/grid.py", line 46, in <module>
    plt.savefig(f'images/lightningData{0}.png', transparent=False, dpi=1000) #Save figure
  File "/home/wrmf/anaconda3/envs/maps/lib/python3.9/site-packages/matplotlib/pyplot.py", line 954, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/wrmf/anaconda3/envs/maps/lib/python3.9/site-packages/matplotlib/figure.py", line 3274, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/wrmf/anaconda3/envs/maps/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2338, in print_figure
    result = print_method(
  File "/home/wrmf/anaconda3/envs/maps/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2204, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/home/wrmf/anaconda3/envs/maps/lib/python3.9/site-packages/matplotlib/_api/deprecation.py", line 410, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/home/wrmf/anaconda3/envs/maps/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 517, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/home/wrmf/anaconda3/envs/maps/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 464, in _print_pil
    mpl.image.imsave(
  File "/home/wrmf/anaconda3/envs/maps/lib/python3.9/site-packages/matplotlib/image.py", line 1664, in imsave
    image.save(fname, **pil_kwargs)
  File "/home/wrmf/anaconda3/envs/maps/lib/python3.9/site-packages/PIL/Image.py", line 2350, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'images/lightningData0.png'
slurmstepd: error: acct_gather_profile/influxdb _send_data: curl_easy_perform failed to send data (discarded). Reason: Couldn't resolve host name
